apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-info
  namespace: web-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ms-info
  template:
    metadata:
      labels:
        app: ms-info
    spec:
      containers:
      - name: ms-info
        image: 271590248982.dkr.ecr.us-east-1.amazonaws.com/poc-devsecops:ms_info
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 1000
          runAsGroup: 3000
        livenessProbe:
          httpGet:
            path: /liveness
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3


        