apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-suggestion
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-suggestion
  template:
    metadata:
      labels:
        app: ms-suggestion
    spec:
      containers:
      - name: ms-suggestion
        image: ms_suggestion:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000