apiVersion: v1
kind: Service
metadata:
  name: ms_suggestion-app-service
  namespace: web-app
spec:
  selector:
    app: ms_suggestion
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer