apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ms-suggestion-vts
  namespace: web-app
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/istio-ingressgateway
  http:
  - match:
    - uri:
        prefix: /ms_suggestion
    route:
    - destination:
        host: ms-suggestion
        port:
          number: 5001
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: blackhole