name: Build ms_info and Push Docker Image to ECR

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build Docker image
      run: |
        docker build -t 271590248982.dkr.ecr.us-east-1.amazonaws.com/poc-devsecops:ms_info -f finance/web/ms_info/src/deployment/docker/dockerfile .  --label test_ms_info

    - name: Run DevSecOps engine Toool secret scan
      run: |
        python -m pip install -q devsecops-engine-tools
        output=$(devsecops-engine-tools --platform_devops github --remote_config_repo devsecops_remote_config --tool engine_secret --folder_path /finance)
          echo "$output"
          if [[ $output == *"✘Failed"* ]]; then
            exit 1
          fi
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: DevSecOps Engine Tool - IaC
      run: |
        pip3 install -q devsecops-engine-tools
        output=$(devsecops-engine-tools --platform_devops github --remote_config_repo devsecops_remote_config --tool engine_iac)
        echo "$output"
        if [[ $output == *"✘Failed"* ]]; then
          exit 1
        fi
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to ECR
      run: |
        docker push 271590248982.dkr.ecr.us-east-1.amazonaws.com/poc-devsecops:ms_info

    - name: DevSecOps Engine Tool - Trivy
      run: |
        pip3 install -q devsecops-engine-tools
        output=$(devsecops-engine-tools --platform_devops github --remote_config_repo devsecops_remote_config --tool engine_container --image_to_scan 271590248982.dkr.ecr.us-east-1.amazonaws.com/poc-devsecops:ms_info)
        echo "$output"
        if [[ $output == *"✘Failed"* ]]; then
          exit 1
        fi
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
