name: Release ms-info to EKS

on:
  push:
    branches:
      - trunk
      - feature/*

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig --region us-east-1 --name poc-devsecops

    - name: Cleanup previous resources
      run: |
        kubectl delete -f finance/web/ms_info/src/deployment/k8s/deployment.yaml -n default || true
        kubectl delete -f finance/web/ms_info/src/deployment/k8s/service.yaml -n default || true

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f finance/web/ms_info/src/deployment/k8s/deployment.yaml
        kubectl apply -f finance/web/ms_info/src/deployment/k8s/service.yaml

    - name: DevSecOps Engine Tool - Trivy
      run: |
        pip3 install -q devsecops-engine-tools
        output=$(devsecops-engine-tools --platform_devops github --remote_config_repo devsecops_remote_config --tool engine_container --image_to_scan poc-devsecops:ms_info)
        echo "$output"
        if [[ $output == *"✘Failed"* ]]; then
          exit 1
        fi
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
